general:
  bot_token: "xxx"
  language: "zh-hans"
  worker_num: 2
  download_worker_num: 3
  admin_uid: 0
  user_daily_limit: 10
  use_ext_file_host: false
  process_wait_queue_max_size: 50

logger:
  report: false
  report_url: ""
  report_query_key: ""

redis:
  server: "localhost"
  port: "6379"
  password: ""
  db: 0