version: "3.9"

services:
  redis:
    image: redis:7
    container_name: sticker_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    image: rroy233/stickerdownloader:latest
    container_name: sticker_app
    depends_on:
      - redis
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./log:/app/log
      - ./storage:/app/storage

volumes:
  redis_data:
