apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-pvc
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-pvc
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sticker-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sticker-app
  template:
    metadata:
      labels:
        app: sticker-app
    spec:
      containers:
        - name: app
          image: rroy233/stickerdownloader:latest
          volumeMounts:
            - name: config
              mountPath: /app/config.yaml
              subPath: config.yaml
            - name: logs
              mountPath: /app/log
            - name: storage
              mountPath: /app/storage
      volumes:
        - name: config
          secret:
            secretName: app-config
        - name: logs
          persistentVolumeClaim:
            claimName: log-pvc
        - name: storage
          persistentVolumeClaim:
            claimName: storage-pvc