name: Docker Multi-Arch Release

on:
  push:
    tags:
      - '*'  # 自动触发：任何 tag 推送都会触发
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image tag to use (e.g., v1.2.3)'
        required: true
        default: 'manual-latest'
      push_latest:
        description: 'Also tag and push as latest?'
        required: false
        default: 'true'

jobs:
  docker:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Aliyun Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ALI_REGISTRY }}
          username: ${{ secrets.ALI_USERNAME }}
          password: ${{ secrets.ALI_PASSWORD }}

      - name: Resolve tag
        id: tag
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "TAG=${{ github.event.inputs.image_tag }}" >> $GITHUB_ENV
            echo "PUSH_LATEST=${{ github.event.inputs.push_latest }}" >> $GITHUB_ENV
          else
            TAG_NAME="${GITHUB_REF##*/}"
            echo "TAG=${TAG_NAME}" >> $GITHUB_ENV
            echo "PUSH_LATEST=true" >> $GITHUB_ENV
          fi

      - name: Show resolved tags
        run: |
          echo "Resolved image tag: $TAG"
          echo "Push latest: $PUSH_LATEST"

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/stickerdownloader:${{ env.TAG }}
            ghcr.io/${{ github.repository_owner }}/stickerdownloader:${{ env.TAG }}
            ${{ secrets.ALI_REGISTRY }}/${{ secrets.ALI_USERNAME }}/stickerdownloader:${{ env.TAG }}
            ${{ env.PUSH_LATEST == 'true' && format('docker.io/{0}/stickerdownloader:latest', secrets.DOCKERHUB_USERNAME) || '' }}
            ${{ env.PUSH_LATEST == 'true' && format('ghcr.io/{0}/stickerdownloader:latest', github.repository_owner) || '' }}
            ${{ env.PUSH_LATEST == 'true' && format('{0}/{1}/stickerdownloader:latest', secrets.ALI_REGISTRY, secrets.ALI_USERNAME) || '' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
